baseurl: https://blog.retompi.com/
languageCode: zh-cn
title: "TomBen’s Blog"
theme: "hugo-tania"
paginate: 10

# GA Tracking ID
googleAnalytics: UA-139205906-1

# Theme i18n support
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 🏄‍♂️️

  # Logo will show before the blog title on site navbar.
  # titleLogo: favicon.ico
  avatar:
        enabled: true
        local: true
        src: avatar.png
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: false
  
  siteName: ""
  siteDesc: ""
  author: "Tom Ben"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github:
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:

# Comments settings
comments:
  enabled: true
  provider: disqus
  disqusShortname: tomben

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
